-- =====================================================================
-- whatsapp-automation - schema.sql  (PostgreSQL / Supabase)
--
-- Como usarlo: Supabase Dashboard -> SQL Editor -> New query ->
-- pega TODO este archivo -> Run. Es seguro ejecutarlo mas de una vez
-- (usa IF NOT EXISTS / DROP ... IF EXISTS / ON CONFLICT).
--
-- Cambios respecto a la version MySQL:
--   * ENUM            -> TEXT + CHECK
--   * TINYINT(1)      -> BOOLEAN
--   * AUTO_INCREMENT  -> GENERATED ... AS IDENTITY
--   * TIMESTAMP       -> TIMESTAMPTZ (zona horaria correcta en la nube)
--   * ON UPDATE CURRENT_TIMESTAMP -> trigger set_updated_at()
--   * JSON            -> JSONB
--   * Redis           -> tablas rate_counters y worker_locks (ver abajo)
-- =====================================================================

-- ---------------------------------------------------------------------
-- Trigger generico para mantener updated_at
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------
-- users: usuarios administrativos del panel
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role TEXT NOT NULL DEFAULT 'AGENT' CHECK (role IN ('ADMIN', 'AGENT')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_users_email UNIQUE (email)
);

-- ---------------------------------------------------------------------
-- sessions: sesiones/tokens activos (reservada; hoy los JWT son stateless)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash VARCHAR(255) NOT NULL,
  user_agent VARCHAR(255),
  ip_address VARCHAR(64),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions (expires_at);

-- ---------------------------------------------------------------------
-- customers: clientes identificados por telefono de WhatsApp
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(32) NOT NULL,
  name VARCHAR(150),
  email VARCHAR(150),
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'BLOCKED', 'ARCHIVED')),
  interest_type TEXT CHECK (interest_type IN ('PRODUCTO', 'SERVICIO', 'INDECISO')),
  interest_level TEXT CHECK (interest_level IN ('BAJO', 'MEDIO', 'ALTO')),
  last_message_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_customers_phone UNIQUE (phone)
);
CREATE INDEX IF NOT EXISTS idx_customers_status ON customers (status);
CREATE INDEX IF NOT EXISTS idx_customers_interest ON customers (interest_type);

-- ---------------------------------------------------------------------
-- conversations: hilos de conversacion por cliente
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'PENDING', 'HUMAN', 'CLOSED')),
  assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_message_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_conversations_customer ON conversations (customer_id);
CREATE INDEX IF NOT EXISTS idx_conversations_status ON conversations (status);
CREATE INDEX IF NOT EXISTS idx_conversations_assigned ON conversations (assigned_to);

-- ---------------------------------------------------------------------
-- messages: mensajes entrantes y salientes
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  direction TEXT NOT NULL CHECK (direction IN ('INBOUND', 'OUTBOUND')),
  message_type TEXT NOT NULL DEFAULT 'TEXT'
    CHECK (message_type IN ('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'DOCUMENT', 'LOCATION', 'OTHER')),
  content TEXT,
  external_message_id VARCHAR(191),
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at TIMESTAMPTZ,
  -- evita registrar dos veces el mismo mensaje entrante de Evolution API
  -- (varios NULL estan permitidos: los mensajes sin id externo no chocan)
  CONSTRAINT uq_messages_external_id UNIQUE (external_message_id)
);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_customer ON messages (customer_id);
CREATE INDEX IF NOT EXISTS idx_messages_status ON messages (status);
CREATE INDEX IF NOT EXISTS idx_messages_created ON messages (created_at);

-- ---------------------------------------------------------------------
-- message_queue: cola de envio
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS message_queue (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  phone VARCHAR(32) NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'CANCELLED', 'PAUSED')),
  attempts INTEGER NOT NULL DEFAULT 0,
  scheduled_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_queue_status ON message_queue (status);
CREATE INDEX IF NOT EXISTS idx_queue_scheduled ON message_queue (scheduled_at);
CREATE INDEX IF NOT EXISTS idx_queue_customer ON message_queue (customer_id);

-- ---------------------------------------------------------------------
-- scheduled_messages: mensajes programados
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scheduled_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  phone VARCHAR(32) NOT NULL,
  message TEXT NOT NULL,
  scheduled_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'SCHEDULED'
    CHECK (status IN ('SCHEDULED', 'QUEUED', 'SENT', 'FAILED', 'CANCELLED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at TIMESTAMPTZ,
  error_message TEXT
);
CREATE INDEX IF NOT EXISTS idx_scheduled_status ON scheduled_messages (status);
CREATE INDEX IF NOT EXISTS idx_scheduled_at ON scheduled_messages (scheduled_at);
CREATE INDEX IF NOT EXISTS idx_scheduled_customer ON scheduled_messages (customer_id);

-- ---------------------------------------------------------------------
-- communication_preferences: opt-in / opt-out por cliente
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS communication_preferences (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  opted_in BOOLEAN NOT NULL DEFAULT TRUE,
  opted_out BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_prefs_customer UNIQUE (customer_id)
);

-- ---------------------------------------------------------------------
-- automation_logs: bitacora de eventos del sistema
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS automation_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(60) NOT NULL,
  level TEXT NOT NULL DEFAULT 'INFO' CHECK (level IN ('INFO', 'WARN', 'ERROR')),
  message TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_logs_event_type ON automation_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_logs_level ON automation_logs (level);
CREATE INDEX IF NOT EXISTS idx_logs_created ON automation_logs (created_at);

-- ---------------------------------------------------------------------
-- system_settings: configuracion global (pause_queue, estado, etc.)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" VARCHAR(100) NOT NULL,
  "value" TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_settings_key UNIQUE ("key")
);

INSERT INTO system_settings ("key", "value") VALUES
  ('automation_status', 'ACTIVE'),
  ('pause_queue', 'false')
ON CONFLICT ("key") DO NOTHING;

-- ---------------------------------------------------------------------
-- NUEVO (reemplaza a Redis): contadores para limites de envio y semaforo
-- de concurrencia. Cada fila tiene su expiracion.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rate_counters (
  counter_key TEXT PRIMARY KEY,
  hits INTEGER NOT NULL DEFAULT 0,
  expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rate_counters_expires ON rate_counters (expires_at);

-- ---------------------------------------------------------------------
-- NUEVO (reemplaza a Redis): candado para que dos ejecuciones del worker
-- (cron cada minuto) no procesen la cola al mismo tiempo.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS worker_locks (
  name TEXT PRIMARY KEY,
  expires_at TIMESTAMPTZ NOT NULL
);

-- ---------------------------------------------------------------------
-- Triggers de updated_at (DROP + CREATE para poder re-ejecutar el script)
-- ---------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_users_updated ON users;
CREATE TRIGGER trg_users_updated BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_customers_updated ON customers;
CREATE TRIGGER trg_customers_updated BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_queue_updated ON message_queue;
CREATE TRIGGER trg_queue_updated BEFORE UPDATE ON message_queue
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_prefs_updated ON communication_preferences;
CREATE TRIGGER trg_prefs_updated BEFORE UPDATE ON communication_preferences
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_settings_updated ON system_settings;
CREATE TRIGGER trg_settings_updated BEFORE UPDATE ON system_settings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- SEGURIDAD (IMPORTANTE en Supabase)
-- Supabase expone por defecto las tablas del esquema `public` mediante
-- su API REST publica (con la anon key). Activar RLS SIN politicas
-- bloquea todo acceso por esa via. El backend NO se ve afectado: se
-- conecta directo a Postgres con el rol `postgres`, que ignora RLS.
-- ---------------------------------------------------------------------
ALTER TABLE users                     ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations             ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_queue             ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_messages        ENABLE ROW LEVEL SECURITY;
ALTER TABLE communication_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_logs           ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings           ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_counters             ENABLE ROW LEVEL SECURITY;
ALTER TABLE worker_locks              ENABLE ROW LEVEL SECURITY;
